export interface SpeciesConfig {
  name: string;
  bodyLength: number;
  bodyHeight: number;
  maxSpeed: number;
  maxForce: number;
  wanderRadius: number;
  wanderDistance: number;
  wanderJitter: number;
  idleChance: number;       // chance per second to enter idle
  idleDurationMin: number;
  idleDurationMax: number;
  tailSize: number;         // relative to body
  tailFrequency: number;    // tail oscillation speed
  dorsalSize: number;
  pectoralSize: number;
  bodyColor: string;
  accentColor: string;
  finColor: string;
  eyeSize: number;
  depthPreference?: 'bottom' | 'surface' | 'mid';
  turnSmoothing: number;    // 0-1, lower = slower turns
}

export const SPECIES: Record<string, SpeciesConfig> = {
  neonTetra: {
    name: 'Neon Tetra',
    bodyLength: 18,
    bodyHeight: 7,
    maxSpeed: 120,
    maxForce: 3.0,
    wanderRadius: 15,
    wanderDistance: 30,
    wanderJitter: 3.0,
    idleChance: 0.05,
    idleDurationMin: 0.5,
    idleDurationMax: 1.0,
    tailSize: 0.4,
    tailFrequency: 12,
    dorsalSize: 0.2,
    pectoralSize: 0.15,
    bodyColor: '#1a8cff',
    accentColor: '#ff3333',
    finColor: '#88ccff',
    eyeSize: 2.5,
    turnSmoothing: 0.15,
  },
  angelfish: {
    name: 'Angelfish',
    bodyLength: 36,
    bodyHeight: 44,
    maxSpeed: 60,
    maxForce: 1.0,
    wanderRadius: 40,
    wanderDistance: 60,
    wanderJitter: 0.8,
    idleChance: 0.3,
    idleDurationMin: 2.0,
    idleDurationMax: 5.0,
    tailSize: 0.3,
    tailFrequency: 5,
    dorsalSize: 0.6,
    pectoralSize: 0.3,
    bodyColor: '#d4d4d4',
    accentColor: '#2a2a2a',
    finColor: '#c0c0c0',
    eyeSize: 3.5,
    turnSmoothing: 0.04,
  },
  guppy: {
    name: 'Guppy',
    bodyLength: 14,
    bodyHeight: 7,
    maxSpeed: 100,
    maxForce: 2.5,
    wanderRadius: 20,
    wanderDistance: 35,
    wanderJitter: 2.0,
    idleChance: 0.15,
    idleDurationMin: 1.0,
    idleDurationMax: 2.0,
    tailSize: 0.6,
    tailFrequency: 10,
    dorsalSize: 0.2,
    pectoralSize: 0.15,
    bodyColor: '#c8c8c8',
    accentColor: '#ff8800',
    finColor: '#ff6622',
    eyeSize: 2.5,
    turnSmoothing: 0.12,
  },
  betta: {
    name: 'Betta',
    bodyLength: 28,
    bodyHeight: 14,
    maxSpeed: 40,
    maxForce: 0.8,
    wanderRadius: 40,
    wanderDistance: 50,
    wanderJitter: 0.5,
    idleChance: 0.25,
    idleDurationMin: 3.0,
    idleDurationMax: 6.0,
    tailSize: 1.0,
    tailFrequency: 3,
    dorsalSize: 0.7,
    pectoralSize: 0.4,
    bodyColor: '#8b0000',
    accentColor: '#4400aa',
    finColor: '#cc2244',
    eyeSize: 3,
    turnSmoothing: 0.03,
  },
  corydoras: {
    name: 'Corydoras',
    bodyLength: 16,
    bodyHeight: 10,
    maxSpeed: 80,
    maxForce: 2.0,
    wanderRadius: 15,
    wanderDistance: 25,
    wanderJitter: 2.0,
    idleChance: 0.2,
    idleDurationMin: 1.0,
    idleDurationMax: 3.0,
    tailSize: 0.3,
    tailFrequency: 8,
    dorsalSize: 0.3,
    pectoralSize: 0.25,
    bodyColor: '#c4a862',
    accentColor: '#6b5530',
    finColor: '#d4b872',
    eyeSize: 2.5,
    depthPreference: 'bottom',
    turnSmoothing: 0.1,
  },
  pleco: {
    name: 'Pleco',
    bodyLength: 42,
    bodyHeight: 16,
    maxSpeed: 10,
    maxForce: 0.3,
    wanderRadius: 10,
    wanderDistance: 15,
    wanderJitter: 0.3,
    idleChance: 0.8,
    idleDurationMin: 10.0,
    idleDurationMax: 30.0,
    tailSize: 0.3,
    tailFrequency: 3,
    dorsalSize: 0.35,
    pectoralSize: 0.3,
    bodyColor: '#3d3020',
    accentColor: '#5a4a30',
    finColor: '#4a3a28',
    eyeSize: 2.5,
    depthPreference: 'bottom',
    turnSmoothing: 0.03,
  },
  dwarfGourami: {
    name: 'Dwarf Gourami',
    bodyLength: 24,
    bodyHeight: 16,
    maxSpeed: 50,
    maxForce: 1.2,
    wanderRadius: 30,
    wanderDistance: 45,
    wanderJitter: 1.2,
    idleChance: 0.2,
    idleDurationMin: 2.0,
    idleDurationMax: 4.0,
    tailSize: 0.35,
    tailFrequency: 6,
    dorsalSize: 0.35,
    pectoralSize: 0.25,
    bodyColor: '#e06030',
    accentColor: '#2090c0',
    finColor: '#e07040',
    eyeSize: 3,
    turnSmoothing: 0.06,
  },
};
